### ISSUE TITLE
build error!

### ISSUE THREAD

**Issue by pokamolodoy406** [SChudakov/crypto#1]
Hello. 
I want to build your programm. 
But... I had error when i did "cmake .":
![Безымянный](https://user-images.githubusercontent.com/37054694/56512625-94c4a500-6538-11e9-933e-0a2d8e393a38.png)

I don't know what googletest is )

**Comment by SChudakov** [comment]
Hi, 
- create a lib/ directory in the project root (the crypto/ directory) 
- navigate to lib/ directory in your terminal
- run git clone https://github.com/google/googletest.git
- you should have lib/googletest/ 
 Should be fine after that.

**Comment by sobolwc** [comment]
> Hi,
> 
>     * create a lib/ directory in the project root (the crypto/ directory)
> 
>     * navigate to lib/ directory in your terminal
> 
>     * run git clone https://github.com/google/googletest.git
> 
>     * you should have lib/googletest/
>       Should be fine after that.

Thank you.
